#pragma line 1 "MadgwickAHRS.cpp" ::: 0
#pragma line 1 "MadgwickAHRS.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 155 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 12
#pragma line 156 "/opt/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 13
#pragma line 8 "<command line>" 2 ::: 143
#pragma line 1 "<built-in>" 2 ::: 144
#pragma line 1 "MadgwickAHRS.cpp" 2 ::: 145
#pragma line 18 "MadgwickAHRS.cpp" ::: 146
#pragma line 1 "./MadgwickAHRS.h" 1 ::: 147
#pragma line 19 "./MadgwickAHRS.h" ::: 148
#pragma line 19 "MadgwickAHRS.cpp" 2 ::: 157
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 158
#pragma line 26 "/usr/include/math.h" 3 4 ::: 159
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 160
#pragma line 345 "/usr/include/features.h" 3 4 ::: 161
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 162
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 163
#pragma line 367 "/usr/include/features.h" 3 4 ::: 164
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 165
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 166
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 167
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 168
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 169
#pragma line 391 "/usr/include/features.h" 3 4 ::: 170
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 171
#pragma line 10 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 3 4 ::: 172
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 173
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 174
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 175
#pragma line 27 "/usr/include/math.h" 2 3 4 ::: 176
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 182
#pragma line 25 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 3 4 ::: 183
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 184
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 185
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 186
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_val.h" 1 3 4 ::: 190
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 191
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_valf.h" 1 3 4 ::: 193
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 194
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_vall.h" 1 3 4 ::: 195
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 196
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/inf.h" 1 3 4 ::: 199
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 200
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/nan.h" 1 3 4 ::: 203
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 204
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 1 3 4 ::: 208
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 209
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 212
#pragma line 83 "/usr/include/math.h" 3 4 ::: 213
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 214
#pragma line 54 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 215
#pragma line 153 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 307
#pragma line 178 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 325
#pragma line 204 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 344
#pragma line 375 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 508
#pragma line 84 "/usr/include/math.h" 2 3 4 ::: 518
#pragma line 104 "/usr/include/math.h" 3 4 ::: 519
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 520
#pragma line 54 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 521
#pragma line 153 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 613
#pragma line 178 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 631
#pragma line 204 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 650
#pragma line 375 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 814
#pragma line 105 "/usr/include/math.h" 2 3 4 ::: 824
#pragma line 151 "/usr/include/math.h" 3 4 ::: 825
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 826
#pragma line 54 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 827
#pragma line 153 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 919
#pragma line 178 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 937
#pragma line 204 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 956
#pragma line 375 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1120
#pragma line 152 "/usr/include/math.h" 2 3 4 ::: 1130
#pragma line 168 "/usr/include/math.h" 3 4 ::: 1131
#pragma line 209 "/usr/include/math.h" 3 4 ::: 1133
#pragma line 347 "/usr/include/math.h" 3 4 ::: 1152
#pragma line 370 "/usr/include/math.h" 3 4 ::: 1166
#pragma line 534 "/usr/include/math.h" 3 4 ::: 1181
#pragma line 20 "MadgwickAHRS.cpp" 2 ::: 1183
#pragma line 30 "MadgwickAHRS.cpp" ::: 1184
