/******************************************************************************
*
* Copyright (C) 2009 - 2014 Xilinx, Inc.  All rights reserved.
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* Use of the Software is limited solely to applications:
* (a) running on a Xilinx device, or
* (b) that interact with a Xilinx device through a bus or interconnect.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
* XILINX  BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
* WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF
* OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
*
* Except as contained in this notice, the name of the Xilinx shall not be used
* in advertising or otherwise to promote the sale, use or other dealings in
* this Software without prior written authorization from Xilinx.
*
******************************************************************************/

/*
 * helloworld.c: simple test application
 *
 * This application configures UART 16550 to baud rate 9600.
 * PS7 UART (Zynq) is not initialized by this application, since
 * bootrom/bsp configures it to baud rate 115200
 *
 * ------------------------------------------------
 * | UART TYPE   BAUD RATE                        |
 * ------------------------------------------------
 *   uartns550   9600
 *   uartlite    Configurable only in HW design
 *   ps7_uart    115200 (configured by bootrom/bsp)
 */

#include <stdio.h>
#include "platform.h"
#include "xil_printf.h"

/*
 * Several BSP (and standard C) header files need to be included
 */
#include <stdlib.h> // Standard C functions, e.g. exit()
#include <stdbool.h> // Provides a Boolean data type for ANSI/ISO-C
#include "xparameters.h" // Parameter definitions for processor peripherals
#include "xscugic.h" // Processor interrupt controller device driver
#include "xupdatetype2.h" // Device driver for HLS HW block

/*
 * Define variables for the HLS block and interrupt controller instance
 * data. The variables will be passed to driver API calls as handles in
 * the respective hardware.
 */
XUpdatetype2 HlsMadgwick; 	// HLS macc HW instance
XScuGic ScuGic; 		//Interrupt Controller Instance
//FATFS SDcard;
/*
 * Define variables for the HLS block and interrupt controller instance
 * data. The variables will be passed to driver API calls as handles in
 * the respective hardware.
 */
volatile static int RunHlsMadgwick = 0;
volatile static int ResultAvailHlsMadgwick = 0;

/*
 * Define a function to wrap all run-once API initialization function
 * calls for the HLS block.
 */
int hls_macc_init(XUpdatetype2 *hls_MadgwickPtr)
{
	XUpdatetype2_Config *cfgPtr;
	int status;
	cfgPtr = XUpdatetype2_LookupConfig(XPAR_UPDATETYPE2_0_DEVICE_ID);
	if (!cfgPtr) {
		print("ERROR: Lookup of accelerator configuration failed.\n\r");
		return XST_FAILURE;
	}
	status = XUpdatetype2_CfgInitialize(hls_MadgwickPtr, cfgPtr);
	if (status != XST_SUCCESS) {
		print("ERROR: Could not initialize accelerator.\n\r");
		return XST_FAILURE;
	}
	return status;
}

/*
 * Define a helper function to wrap the HLS block API calls required to
 * enable its interrupt and start the block
 */
void hls_madgwick_start(void *InstancePtr){
	XUpdatetype2 *pAccelerator = (XUpdatetype2 *)InstancePtr;
	XUpdatetype2_InterruptEnable(pAccelerator,1);
	XUpdatetype2_InterruptGlobalEnable(pAccelerator);
	XUpdatetype2_Start(pAccelerator);
}

/*
 * An interrupt service routine is required in order for the processor
 * to respond to an interrupt generated by a peripheral. Each peripheral
 * with an interrupt attached to the PS must have an ISR defined and
 * registered with the PS’s interrupt handler.
 */
void hls_macc_isr(void *InstancePtr){
	XUpdatetype2 *pAccelerator = (XUpdatetype2 *)InstancePtr;
	//Disable the global interrupt
	XUpdatetype2_InterruptGlobalDisable(pAccelerator);
	//Disable the local interrupt
	XUpdatetype2_InterruptDisable(pAccelerator,0xffffffff);
	// clear the local interrupt
	XUpdatetype2_InterruptClear(pAccelerator,1);
	ResultAvailHlsMadgwick = 1;
	// restart the core if it should run again
	if(RunHlsMadgwick){
		hls_madgwick_start(pAccelerator);
	}
}

/*
 * Define a routine to setup the PS interrupt handler and register the
 * HLS peripheral’s ISR.
 */
int setup_interrupt()
{
	//This functions sets up the interrupt on the ARM
	int result;
	XScuGic_Config *pCfg = XScuGic_LookupConfig(XPAR_SCUGIC_SINGLE_DEVICE_ID);
	if (pCfg == NULL){
		print("Interrupt Configuration Lookup Failed\n\r");
		return XST_FAILURE;
	}
	result = XScuGic_CfgInitialize(&ScuGic,pCfg,pCfg->CpuBaseAddress);

	if(result != XST_SUCCESS){
		return result;
	}
	// self-test
	result = XScuGic_SelfTest(&ScuGic);

	if(result != XST_SUCCESS){
		return result;
	}

	// Initialize the exception handler
	Xil_ExceptionInit();
	// Register the exception handler
	//print("Register the exception handler\n\r");
	Xil_ExceptionRegisterHandler(XIL_EXCEPTION_ID_INT,
	(Xil_ExceptionHandler)XScuGic_InterruptHandler,&ScuGic);
	//Enable the exception handler
	Xil_ExceptionEnable();
	// Connect the Adder ISR to the exception table
	//print("Connect the Adder ISR to the Exception handler table\n\r");
	result = XScuGic_Connect(&ScuGic, XPAR_FABRIC_UPDATETYPE2_0_INTERRUPT_INTR,
	(Xil_InterruptHandler)hls_macc_isr,&HlsMadgwick);
	if(result != XST_SUCCESS){
		return result;
	}
	//print("Enable the Adder ISR\n\r");
	XScuGic_Enable(&ScuGic,XPAR_FABRIC_UPDATETYPE2_0_INTERRUPT_INTR);
	return XST_SUCCESS;
}
int main()
{
	int main()
	{
		print("Program to compare implementaion of Madgwick algorithm in hw and sw\n\r");
		int m[3], a[3], g[3], q_in[4], q_out[4], euler[3];
		int res_hw;
		int res_sw;
		int status;

		//Setup the madgwick HLS
		status = hls_macc_init(&HlsMadgwick);
		if(status != XST_SUCCESS){
			print("HLS peripheral setup failed\n\r");
			exit(-1);
		}

		//Setup the interrupt
		status = setup_interrupt();
		if(status != XST_SUCCESS){
			print("Interrupt setup failed\n\r");
			exit(-1);
		}

		//set the input parameters of the HLS block
		XUpdatetype2_Write_g_Words(&HlsMadgwick, XUPDATETYPE2_BUS_COPROCESSOR_ADDR_G_BASE, g, 3);
		XUpdatetype2_Write_a_Words(&HlsMadgwick, XUPDATETYPE2_BUS_COPROCESSOR_ADDR_A_BASE, a, 3);
		XUpdatetype2_Write_m_Words(&HlsMadgwick, XUPDATETYPE2_BUS_COPROCESSOR_ADDR_M_BASE, m, 3);
		XUpdatetype2_Write_q_Words(&HlsMadgwick, XUPDATETYPE2_BUS_COPROCESSOR_ADDR_Q_BASE, q_in, 4);
		XUpdatetype2_Write_euler_Words(&HlsMadgwick, XUPDATETYPE2_BUS_COPROCESSOR_ADDR_EULER_BASE, euler, 3);

		if (XUpdatetype2_IsReady(&HlsMadgwick))
			print("HLS peripheral is ready. Starting... ");
		else {
			print("!!! HLS peripheral is not ready! Exiting...\n\r");
		exit(-1);
		}

		if (0) { // use interrupt
			hls_madgwick_start(&HlsMadgwick);
			while(!ResultAvailHlsMadgwick)
				; // spin
			XUpdatetype2_Read_q_Words(&HlsMadgwick, XUPDATETYPE2_BUS_COPROCESSOR_ADDR_Q_BASE, q_out, 4);
			XUpdatetype2_Read_euler_Words(&HlsMadgwick, XUPDATETYPE2_BUS_COPROCESSOR_ADDR_EULER_BASE, euler, 3);
//			res_hw = XHls_macc_GetAccum(&HlsMacc);
			print("Interrupt received from HLS HW.\n\r");
		}
		else { // Simple non-interrupt driven test
			XUpdatetype2_Start(&HlsMadgwick);
			do {
				XUpdatetype2_Read_q_Words(&HlsMadgwick, XUPDATETYPE2_BUS_COPROCESSOR_ADDR_Q_BASE, q_out, 4);
				XUpdatetype2_Read_euler_Words(&HlsMadgwick, XUPDATETYPE2_BUS_COPROCESSOR_ADDR_EULER_BASE, euler, 3);
//				res_hw = XHls_macc_Get_accum(&HlsMacc);
			} while (!XUpdatetype2_IsReady(&HlsMadgwick));
				print("Detected HLS peripheral complete. Result received.\n\r");
		}
	//	while(1){
		//call the software version of the function
//		sw_macc(a, b, &res_sw, false);
		printf("Result from HW: %d; Result from SW: %d\n\r", res_hw, res_sw);
		if (res_hw == res_sw) {
			print("*** Results match ***\n\r");
			status = 0;
		}
		else {
			print("!!! MISMATCH !!!\n\r");
			status = -1;
		}
		cleanup_platform();
		return status;//}
	}
}
