#pragma line 1 "MadgwickAHRS.cpp" ::: -10
#pragma line 1 "MadgwickAHRS.cpp" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 155 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 2
#pragma line 156 "/opt/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 3
#pragma line 8 "<command line>" 2 ::: 133
#pragma line 1 "<built-in>" 2 ::: 134
#pragma line 1 "MadgwickAHRS.cpp" 2 ::: 135
#pragma line 26 "MadgwickAHRS.cpp" ::: 136
#pragma line 1 "./MadgwickAHRS.h" 1 ::: 137
#pragma line 26 "./MadgwickAHRS.h" ::: 138
#pragma line 27 "MadgwickAHRS.cpp" 2 ::: 151
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 153
#pragma line 26 "/usr/include/math.h" 3 4 ::: 154
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 155
#pragma line 345 "/usr/include/features.h" 3 4 ::: 156
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 157
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 158
#pragma line 367 "/usr/include/features.h" 3 4 ::: 159
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 160
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 161
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 162
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 163
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 164
#pragma line 391 "/usr/include/features.h" 3 4 ::: 165
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 166
#pragma line 10 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 3 4 ::: 167
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 168
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 169
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 170
#pragma line 27 "/usr/include/math.h" 2 3 4 ::: 171
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 177
#pragma line 25 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 3 4 ::: 178
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 179
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 180
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 181
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_val.h" 1 3 4 ::: 185
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 186
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_valf.h" 1 3 4 ::: 188
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 189
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_vall.h" 1 3 4 ::: 190
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 191
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/inf.h" 1 3 4 ::: 194
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 195
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/nan.h" 1 3 4 ::: 198
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 199
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 1 3 4 ::: 203
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 204
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 207
#pragma line 83 "/usr/include/math.h" 3 4 ::: 208
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 209
#pragma line 54 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 210
#pragma line 153 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 302
#pragma line 178 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 320
#pragma line 204 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 339
#pragma line 375 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 503
#pragma line 84 "/usr/include/math.h" 2 3 4 ::: 513
#pragma line 104 "/usr/include/math.h" 3 4 ::: 514
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 515
#pragma line 54 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 516
#pragma line 153 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 608
#pragma line 178 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 626
#pragma line 204 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 645
#pragma line 375 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 809
#pragma line 105 "/usr/include/math.h" 2 3 4 ::: 819
#pragma line 151 "/usr/include/math.h" 3 4 ::: 820
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 821
#pragma line 54 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 822
#pragma line 153 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 914
#pragma line 178 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 932
#pragma line 204 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 951
#pragma line 375 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1115
#pragma line 152 "/usr/include/math.h" 2 3 4 ::: 1125
#pragma line 168 "/usr/include/math.h" 3 4 ::: 1126
#pragma line 209 "/usr/include/math.h" 3 4 ::: 1128
#pragma line 347 "/usr/include/math.h" 3 4 ::: 1147
#pragma line 370 "/usr/include/math.h" 3 4 ::: 1161
#pragma line 534 "/usr/include/math.h" 3 4 ::: 1176
#pragma line 28 "MadgwickAHRS.cpp" 2 ::: 1178
#pragma line 28 "MadgwickAHRS.cpp" ::: 1180
