#pragma line 1 "MadgwickAHRS.cpp" ::: 0
#pragma line 1 "MadgwickAHRS.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 155 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 12
#pragma line 156 "/opt/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 13
#pragma line 8 "<command line>" 2 ::: 143
#pragma line 1 "<built-in>" 2 ::: 144
#pragma line 1 "MadgwickAHRS.cpp" 2 ::: 145
#pragma line 26 "MadgwickAHRS.cpp" ::: 146
#pragma line 1 "./MadgwickAHRS.h" 1 ::: 147
#pragma line 26 "./MadgwickAHRS.h" ::: 148
#pragma line 27 "MadgwickAHRS.cpp" 2 ::: 161
#pragma line 1 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 1 3 ::: 163
#pragma line 41 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 3 ::: 164
#pragma line 41 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 3 ::: 165
#pragma line 1 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 1 3 ::: 167
#pragma line 153 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 3 ::: 168
#pragma line 393 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 3 ::: 178
#pragma line 1 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/os_defines.h" 1 3 ::: 179
#pragma line 40 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/os_defines.h" 3 ::: 180
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 181
#pragma line 345 "/usr/include/features.h" 3 4 ::: 182
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 183
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 184
#pragma line 367 "/usr/include/features.h" 3 4 ::: 185
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 186
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 187
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 188
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 189
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 190
#pragma line 391 "/usr/include/features.h" 3 4 ::: 191
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 192
#pragma line 10 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 3 4 ::: 193
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 194
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 195
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 196
#pragma line 41 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/os_defines.h" 2 3 ::: 197
#pragma line 394 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 2 3 ::: 198
#pragma line 1 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/cpu_defines.h" 1 3 ::: 201
#pragma line 397 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 2 3 ::: 202
#pragma line 43 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 2 3 ::: 203
#pragma line 1 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/cpp_type_traits.h" 1 3 ::: 204
#pragma line 36 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/cpp_type_traits.h" 3 ::: 205
#pragma line 36 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/cpp_type_traits.h" 3 ::: 206
#pragma line 68 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/cpp_type_traits.h" 3 ::: 207
#pragma line 198 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/cpp_type_traits.h" 3 ::: 320
#pragma line 422 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/cpp_type_traits.h" 3 ::: 531
#pragma line 44 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 2 3 ::: 533
#pragma line 1 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ext/type_traits.h" 1 3 ::: 534
#pragma line 33 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ext/type_traits.h" 3 ::: 535
#pragma line 33 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ext/type_traits.h" 3 ::: 536
#pragma line 45 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 2 3 ::: 716
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 717
#pragma line 28 "/usr/include/math.h" 3 4 ::: 718
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 723
#pragma line 25 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 3 4 ::: 724
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 725
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 726
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 727
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_val.h" 1 3 4 ::: 731
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 732
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_valf.h" 1 3 4 ::: 734
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 735
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_vall.h" 1 3 4 ::: 736
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 737
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/inf.h" 1 3 4 ::: 740
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 741
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/nan.h" 1 3 4 ::: 744
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 745
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 1 3 4 ::: 749
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 750
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 753
#pragma line 83 "/usr/include/math.h" 3 4 ::: 754
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 755
#pragma line 54 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 756
#pragma line 153 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 848
#pragma line 178 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 866
#pragma line 204 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 885
#pragma line 375 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1049
#pragma line 84 "/usr/include/math.h" 2 3 4 ::: 1059
#pragma line 104 "/usr/include/math.h" 3 4 ::: 1060
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 1061
#pragma line 54 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1062
#pragma line 153 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1154
#pragma line 178 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1172
#pragma line 204 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1191
#pragma line 375 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1355
#pragma line 105 "/usr/include/math.h" 2 3 4 ::: 1365
#pragma line 151 "/usr/include/math.h" 3 4 ::: 1366
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 1367
#pragma line 54 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1368
#pragma line 153 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1460
#pragma line 178 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1478
#pragma line 204 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1497
#pragma line 375 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1661
#pragma line 152 "/usr/include/math.h" 2 3 4 ::: 1671
#pragma line 168 "/usr/include/math.h" 3 4 ::: 1672
#pragma line 209 "/usr/include/math.h" 3 4 ::: 1674
#pragma line 347 "/usr/include/math.h" 3 4 ::: 1693
#pragma line 370 "/usr/include/math.h" 3 4 ::: 1707
#pragma line 534 "/usr/include/math.h" 3 4 ::: 1722
#pragma line 46 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 2 3 ::: 1724
#pragma line 76 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 3 ::: 1725
#pragma line 480 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 3 ::: 2112
#pragma line 730 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 3 ::: 2115
#pragma line 29 "MadgwickAHRS.cpp" 2 ::: 2229
