#pragma line 1 "MadgwickAHRS.cpp" ::: -10
#pragma line 1 "MadgwickAHRS.cpp" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 155 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 2
#pragma line 156 "/opt/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 3
#pragma line 8 "<command line>" 2 ::: 133
#pragma line 1 "<built-in>" 2 ::: 134
#pragma line 1 "MadgwickAHRS.cpp" 2 ::: 135
#pragma line 26 "MadgwickAHRS.cpp" ::: 136
#pragma line 1 "./MadgwickAHRS.h" 1 ::: 137
#pragma line 26 "./MadgwickAHRS.h" ::: 138
#pragma line 27 "MadgwickAHRS.cpp" 2 ::: 151
#pragma line 1 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 1 3 ::: 153
#pragma line 41 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 3 ::: 154
#pragma line 41 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 3 ::: 155
#pragma line 1 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 1 3 ::: 157
#pragma line 153 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 3 ::: 158
#pragma line 393 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 3 ::: 168
#pragma line 1 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/os_defines.h" 1 3 ::: 169
#pragma line 40 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/os_defines.h" 3 ::: 170
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 171
#pragma line 345 "/usr/include/features.h" 3 4 ::: 172
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 173
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 174
#pragma line 367 "/usr/include/features.h" 3 4 ::: 175
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 176
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 177
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 178
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 179
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 180
#pragma line 391 "/usr/include/features.h" 3 4 ::: 181
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 182
#pragma line 10 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 3 4 ::: 183
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 184
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 185
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 186
#pragma line 41 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/os_defines.h" 2 3 ::: 187
#pragma line 394 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 2 3 ::: 188
#pragma line 1 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/cpu_defines.h" 1 3 ::: 191
#pragma line 397 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 2 3 ::: 192
#pragma line 43 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 2 3 ::: 193
#pragma line 1 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/cpp_type_traits.h" 1 3 ::: 194
#pragma line 36 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/cpp_type_traits.h" 3 ::: 195
#pragma line 36 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/cpp_type_traits.h" 3 ::: 196
#pragma line 68 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/cpp_type_traits.h" 3 ::: 197
#pragma line 198 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/cpp_type_traits.h" 3 ::: 310
#pragma line 422 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/cpp_type_traits.h" 3 ::: 521
#pragma line 44 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 2 3 ::: 523
#pragma line 1 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ext/type_traits.h" 1 3 ::: 524
#pragma line 33 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ext/type_traits.h" 3 ::: 525
#pragma line 33 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ext/type_traits.h" 3 ::: 526
#pragma line 45 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 2 3 ::: 706
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 708
#pragma line 28 "/usr/include/math.h" 3 4 ::: 709
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 714
#pragma line 25 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 3 4 ::: 715
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 716
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 717
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 718
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_val.h" 1 3 4 ::: 722
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 723
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_valf.h" 1 3 4 ::: 725
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 726
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_vall.h" 1 3 4 ::: 727
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 728
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/inf.h" 1 3 4 ::: 731
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 732
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/nan.h" 1 3 4 ::: 735
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 736
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 1 3 4 ::: 740
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 741
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 744
#pragma line 83 "/usr/include/math.h" 3 4 ::: 745
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 746
#pragma line 54 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 747
#pragma line 153 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 839
#pragma line 178 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 857
#pragma line 204 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 876
#pragma line 375 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1040
#pragma line 84 "/usr/include/math.h" 2 3 4 ::: 1050
#pragma line 104 "/usr/include/math.h" 3 4 ::: 1051
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 1052
#pragma line 54 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1053
#pragma line 153 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1145
#pragma line 178 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1163
#pragma line 204 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1182
#pragma line 375 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1346
#pragma line 105 "/usr/include/math.h" 2 3 4 ::: 1356
#pragma line 151 "/usr/include/math.h" 3 4 ::: 1357
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 1358
#pragma line 54 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1359
#pragma line 153 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1451
#pragma line 178 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1469
#pragma line 204 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1488
#pragma line 375 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1652
#pragma line 152 "/usr/include/math.h" 2 3 4 ::: 1662
#pragma line 168 "/usr/include/math.h" 3 4 ::: 1663
#pragma line 209 "/usr/include/math.h" 3 4 ::: 1665
#pragma line 347 "/usr/include/math.h" 3 4 ::: 1684
#pragma line 370 "/usr/include/math.h" 3 4 ::: 1698
#pragma line 534 "/usr/include/math.h" 3 4 ::: 1713
#pragma line 46 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 2 3 ::: 1715
#pragma line 46 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" ::: 1717
#pragma line 76 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 3 ::: 1719
#pragma line 480 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 3 ::: 2106
#pragma line 730 "/opt/Xilinx/Vivado/2017.3/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cmath" 3 ::: 2109
#pragma line 29 "MadgwickAHRS.cpp" 2 ::: 2223
#pragma line 209 "MadgwickAHRS.cpp" ::: 2406
#pragma line 216 "MadgwickAHRS.cpp" ::: 2416
#pragma line 229 "MadgwickAHRS.cpp" ::: 2432
#pragma line 239 "MadgwickAHRS.cpp" ::: 2445
