// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _normalise_1_HH_
#define _normalise_1_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "MadgwickAHRSupdatbkb.h"
#include "MadgwickAHRSupdatcud.h"
#include "MadgwickAHRSupdatdEe.h"

namespace ap_rtl {

struct normalise_1 : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > in_0_read;
    sc_in< sc_lv<32> > in_1_read;
    sc_in< sc_lv<32> > in_2_read;
    sc_in< sc_lv<32> > in_3_read;
    sc_out< sc_lv<32> > ap_return_0;
    sc_out< sc_lv<32> > ap_return_1;
    sc_out< sc_lv<32> > ap_return_2;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<32> > ap_var_for_const1;
    sc_signal< sc_lv<5> > ap_var_for_const2;


    // Module declarations
    normalise_1(sc_module_name name);
    SC_HAS_PROCESS(normalise_1);

    ~normalise_1();

    sc_trace_file* mVcdFile;

    MadgwickAHRSupdatbkb<1,9,32,32,32>* MadgwickAHRSupdatbkb_U8;
    MadgwickAHRSupdatcud<1,5,32,32,32>* MadgwickAHRSupdatcud_U9;
    MadgwickAHRSupdatdEe<1,4,32,32,1>* MadgwickAHRSupdatdEe_U10;
    sc_signal< sc_lv<75> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > grp_fu_142_p2;
    sc_signal< sc_lv<32> > reg_152;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_logic > ap_CS_fsm_state24;
    sc_signal< sc_lv<1> > tmp_7_reg_382;
    sc_signal< sc_logic > ap_CS_fsm_state39;
    sc_signal< sc_logic > ap_CS_fsm_state44;
    sc_signal< sc_logic > ap_CS_fsm_state49;
    sc_signal< sc_logic > ap_CS_fsm_state63;
    sc_signal< sc_logic > ap_CS_fsm_state74;
    sc_signal< sc_lv<32> > grp_fu_136_p2;
    sc_signal< sc_lv<32> > reg_159;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_logic > ap_CS_fsm_state33;
    sc_signal< sc_logic > ap_CS_fsm_state58;
    sc_signal< sc_lv<32> > in_load_1_phi_fu_193_p3;
    sc_signal< sc_lv<32> > in_load_1_phi_reg_371;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > exitcond1_fu_165_p2;
    sc_signal< sc_lv<3> > i_1_fu_200_p2;
    sc_signal< sc_lv<3> > i_1_reg_377;
    sc_signal< sc_lv<1> > tmp_7_fu_241_p2;
    sc_signal< sc_logic > ap_CS_fsm_state19;
    sc_signal< sc_lv<32> > SumOfSquare_3_fu_247_p3;
    sc_signal< sc_lv<32> > SumOfSquare_3_reg_388;
    sc_signal< sc_logic > ap_CS_fsm_state34;
    sc_signal< sc_lv<31> > tmp_i_reg_394;
    sc_signal< sc_logic > ap_CS_fsm_state35;
    sc_signal< sc_lv<32> > y_1_fu_270_p2;
    sc_signal< sc_lv<32> > y_1_reg_399;
    sc_signal< sc_lv<32> > tmp_i_4_fu_276_p1;
    sc_signal< sc_lv<32> > tmp_i_4_reg_404;
    sc_signal< sc_logic > ap_CS_fsm_state40;
    sc_signal< sc_lv<1> > cond_fu_286_p2;
    sc_signal< sc_lv<1> > cond_reg_413;
    sc_signal< sc_logic > ap_CS_fsm_state64;
    sc_signal< sc_lv<1> > exitcond_fu_280_p2;
    sc_signal< sc_lv<32> > in_load_3_phi_fu_292_p3;
    sc_signal< sc_lv<32> > in_load_3_phi_reg_419;
    sc_signal< sc_lv<2> > i_2_fu_300_p2;
    sc_signal< sc_lv<2> > i_2_reg_424;
    sc_signal< sc_lv<32> > tmp_s_reg_429;
    sc_signal< sc_logic > ap_CS_fsm_state69;
    sc_signal< sc_lv<32> > in2_1_fu_306_p3;
    sc_signal< sc_logic > ap_CS_fsm_state70;
    sc_signal< sc_lv<32> > in12_1_fu_312_p3;
    sc_signal< sc_lv<3> > i_reg_82;
    sc_signal< sc_lv<32> > SumOfSquare_reg_93;
    sc_signal< sc_lv<32> > in2_reg_105;
    sc_signal< sc_lv<32> > in_reg_115;
    sc_signal< sc_lv<2> > i1_reg_125;
    sc_signal< sc_lv<32> > grp_fu_136_p0;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_logic > ap_CS_fsm_state25;
    sc_signal< sc_logic > ap_CS_fsm_state50;
    sc_signal< sc_lv<32> > grp_fu_142_p0;
    sc_signal< sc_lv<32> > grp_fu_142_p1;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > ap_CS_fsm_state20;
    sc_signal< sc_logic > ap_CS_fsm_state45;
    sc_signal< sc_logic > ap_CS_fsm_state59;
    sc_signal< sc_logic > ap_CS_fsm_state65;
    sc_signal< sc_lv<2> > tmp_9_fu_171_p1;
    sc_signal< sc_lv<1> > sel_tmp_fu_175_p2;
    sc_signal< sc_lv<1> > sel_tmp2_fu_187_p2;
    sc_signal< sc_lv<32> > sel_tmp1_fu_181_p3;
    sc_signal< sc_lv<32> > in_0_read_to_int_fu_206_p1;
    sc_signal< sc_lv<8> > tmp_fu_209_p4;
    sc_signal< sc_lv<23> > tmp_1_fu_219_p1;
    sc_signal< sc_lv<1> > notrhs_fu_229_p2;
    sc_signal< sc_lv<1> > notlhs_fu_223_p2;
    sc_signal< sc_lv<1> > tmp_4_fu_235_p2;
    sc_signal< sc_lv<1> > grp_fu_147_p2;
    sc_signal< sc_lv<32> > y_fu_254_p1;
    sc_signal< sc_lv<32> > tmp_8_fu_267_p1;
    sc_signal< sc_logic > ap_CS_fsm_state75;
    sc_signal< sc_lv<32> > in_0_write_assign_fu_318_p3;
    sc_signal< sc_lv<2> > grp_fu_136_opcode;
    sc_signal< sc_lv<75> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<75> ap_ST_fsm_state1;
    static const sc_lv<75> ap_ST_fsm_state2;
    static const sc_lv<75> ap_ST_fsm_state3;
    static const sc_lv<75> ap_ST_fsm_state4;
    static const sc_lv<75> ap_ST_fsm_state5;
    static const sc_lv<75> ap_ST_fsm_state6;
    static const sc_lv<75> ap_ST_fsm_state7;
    static const sc_lv<75> ap_ST_fsm_state8;
    static const sc_lv<75> ap_ST_fsm_state9;
    static const sc_lv<75> ap_ST_fsm_state10;
    static const sc_lv<75> ap_ST_fsm_state11;
    static const sc_lv<75> ap_ST_fsm_state12;
    static const sc_lv<75> ap_ST_fsm_state13;
    static const sc_lv<75> ap_ST_fsm_state14;
    static const sc_lv<75> ap_ST_fsm_state15;
    static const sc_lv<75> ap_ST_fsm_state16;
    static const sc_lv<75> ap_ST_fsm_state17;
    static const sc_lv<75> ap_ST_fsm_state18;
    static const sc_lv<75> ap_ST_fsm_state19;
    static const sc_lv<75> ap_ST_fsm_state20;
    static const sc_lv<75> ap_ST_fsm_state21;
    static const sc_lv<75> ap_ST_fsm_state22;
    static const sc_lv<75> ap_ST_fsm_state23;
    static const sc_lv<75> ap_ST_fsm_state24;
    static const sc_lv<75> ap_ST_fsm_state25;
    static const sc_lv<75> ap_ST_fsm_state26;
    static const sc_lv<75> ap_ST_fsm_state27;
    static const sc_lv<75> ap_ST_fsm_state28;
    static const sc_lv<75> ap_ST_fsm_state29;
    static const sc_lv<75> ap_ST_fsm_state30;
    static const sc_lv<75> ap_ST_fsm_state31;
    static const sc_lv<75> ap_ST_fsm_state32;
    static const sc_lv<75> ap_ST_fsm_state33;
    static const sc_lv<75> ap_ST_fsm_state34;
    static const sc_lv<75> ap_ST_fsm_state35;
    static const sc_lv<75> ap_ST_fsm_state36;
    static const sc_lv<75> ap_ST_fsm_state37;
    static const sc_lv<75> ap_ST_fsm_state38;
    static const sc_lv<75> ap_ST_fsm_state39;
    static const sc_lv<75> ap_ST_fsm_state40;
    static const sc_lv<75> ap_ST_fsm_state41;
    static const sc_lv<75> ap_ST_fsm_state42;
    static const sc_lv<75> ap_ST_fsm_state43;
    static const sc_lv<75> ap_ST_fsm_state44;
    static const sc_lv<75> ap_ST_fsm_state45;
    static const sc_lv<75> ap_ST_fsm_state46;
    static const sc_lv<75> ap_ST_fsm_state47;
    static const sc_lv<75> ap_ST_fsm_state48;
    static const sc_lv<75> ap_ST_fsm_state49;
    static const sc_lv<75> ap_ST_fsm_state50;
    static const sc_lv<75> ap_ST_fsm_state51;
    static const sc_lv<75> ap_ST_fsm_state52;
    static const sc_lv<75> ap_ST_fsm_state53;
    static const sc_lv<75> ap_ST_fsm_state54;
    static const sc_lv<75> ap_ST_fsm_state55;
    static const sc_lv<75> ap_ST_fsm_state56;
    static const sc_lv<75> ap_ST_fsm_state57;
    static const sc_lv<75> ap_ST_fsm_state58;
    static const sc_lv<75> ap_ST_fsm_state59;
    static const sc_lv<75> ap_ST_fsm_state60;
    static const sc_lv<75> ap_ST_fsm_state61;
    static const sc_lv<75> ap_ST_fsm_state62;
    static const sc_lv<75> ap_ST_fsm_state63;
    static const sc_lv<75> ap_ST_fsm_state64;
    static const sc_lv<75> ap_ST_fsm_state65;
    static const sc_lv<75> ap_ST_fsm_state66;
    static const sc_lv<75> ap_ST_fsm_state67;
    static const sc_lv<75> ap_ST_fsm_state68;
    static const sc_lv<75> ap_ST_fsm_state69;
    static const sc_lv<75> ap_ST_fsm_state70;
    static const sc_lv<75> ap_ST_fsm_state71;
    static const sc_lv<75> ap_ST_fsm_state72;
    static const sc_lv<75> ap_ST_fsm_state73;
    static const sc_lv<75> ap_ST_fsm_state74;
    static const sc_lv<75> ap_ST_fsm_state75;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_26;
    static const sc_lv<32> ap_const_lv32_2B;
    static const sc_lv<32> ap_const_lv32_30;
    static const sc_lv<32> ap_const_lv32_3E;
    static const sc_lv<32> ap_const_lv32_49;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_20;
    static const sc_lv<32> ap_const_lv32_39;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_21;
    static const sc_lv<32> ap_const_lv32_22;
    static const sc_lv<32> ap_const_lv32_27;
    static const sc_lv<32> ap_const_lv32_3F;
    static const sc_lv<32> ap_const_lv32_44;
    static const sc_lv<32> ap_const_lv32_45;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<32> ap_const_lv32_3FC00000;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_31;
    static const sc_lv<32> ap_const_lv32_3F000000;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<32> ap_const_lv32_2C;
    static const sc_lv<32> ap_const_lv32_3A;
    static const sc_lv<32> ap_const_lv32_40;
    static const sc_lv<3> ap_const_lv3_4;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<23> ap_const_lv23_0;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_5F3759DF;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<32> ap_const_lv32_4A;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const2();
    void thread_ap_clk_no_reset_();
    void thread_SumOfSquare_3_fu_247_p3();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state19();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state20();
    void thread_ap_CS_fsm_state24();
    void thread_ap_CS_fsm_state25();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state33();
    void thread_ap_CS_fsm_state34();
    void thread_ap_CS_fsm_state35();
    void thread_ap_CS_fsm_state39();
    void thread_ap_CS_fsm_state40();
    void thread_ap_CS_fsm_state44();
    void thread_ap_CS_fsm_state45();
    void thread_ap_CS_fsm_state49();
    void thread_ap_CS_fsm_state50();
    void thread_ap_CS_fsm_state58();
    void thread_ap_CS_fsm_state59();
    void thread_ap_CS_fsm_state63();
    void thread_ap_CS_fsm_state64();
    void thread_ap_CS_fsm_state65();
    void thread_ap_CS_fsm_state69();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state70();
    void thread_ap_CS_fsm_state74();
    void thread_ap_CS_fsm_state75();
    void thread_ap_CS_fsm_state8();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_ap_return_2();
    void thread_cond_fu_286_p2();
    void thread_exitcond1_fu_165_p2();
    void thread_exitcond_fu_280_p2();
    void thread_grp_fu_136_opcode();
    void thread_grp_fu_136_p0();
    void thread_grp_fu_142_p0();
    void thread_grp_fu_142_p1();
    void thread_i_1_fu_200_p2();
    void thread_i_2_fu_300_p2();
    void thread_in12_1_fu_312_p3();
    void thread_in2_1_fu_306_p3();
    void thread_in_0_read_to_int_fu_206_p1();
    void thread_in_0_write_assign_fu_318_p3();
    void thread_in_load_1_phi_fu_193_p3();
    void thread_in_load_3_phi_fu_292_p3();
    void thread_notlhs_fu_223_p2();
    void thread_notrhs_fu_229_p2();
    void thread_sel_tmp1_fu_181_p3();
    void thread_sel_tmp2_fu_187_p2();
    void thread_sel_tmp_fu_175_p2();
    void thread_tmp_1_fu_219_p1();
    void thread_tmp_4_fu_235_p2();
    void thread_tmp_7_fu_241_p2();
    void thread_tmp_8_fu_267_p1();
    void thread_tmp_9_fu_171_p1();
    void thread_tmp_fu_209_p4();
    void thread_tmp_i_4_fu_276_p1();
    void thread_y_1_fu_270_p2();
    void thread_y_fu_254_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
